name: Python CI

on:
  workflow_dispatch:
    inputs:
      model_type:
        description: "Model type"
        required: true
        default: "LSTM"
        type: choice
        options:
          - LSTM
          - Attention

      epoch_number:
        description: "Epoch number"
        required: true
        default: "10"
        type: choice
        options:
          - 2
          - 5
          - 10
          - 50

      batch_size:
        description: "Batch Size"
        required: true
        default: "14"
        type: choice
        options:
          - 5
          - 10
          - 14
          - 20
          - 32
  # For automated triggers;
  # push:
  #   branches:
  #     - main
env:
  FLICKER_8K_TEXT: "1sIxT8WrW21vaQvUY3BLGnnmAY-ocZhpO"
  FLICKER_8K_IMAGE: "176wGCHHp2DpoDblsliEkX4fTpfQUbZOq"

jobs:
  build:
    runs-on: ubuntu-latest

    if: ${{ inputs.epoch_number }}
    steps:
      - name: "Executing for Epoch ${{ inputs.epoch_number }}"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pipenv"

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel gdown

      - name: Install dependencies
        run: |
          pipenv install --deploy --dev --verbose
          pipenv install gtts
          sudo apt-get install -y mpg321

      - name: Download DS dataset
        run: |
          gdown "${{env.FLICKER_8K_TEXT}}" -O datasets/download_ds_file.zip

      - name: Download Image dataset
        run: |
          gdown "${{env.FLICKER_8K_IMAGE}}" -O datasets/download_image_file.zip

      - name: Extract ZIP file
        run: unzip datasets/download_image_file.zip -d datasets

      - name: Check if file exists
        run: |
          chmod +x scripts/ 
          ./scripts/check_file_exists.sh datasets/*.zip

      - name: Set write permissions for datasets directory
        run: chmod -R +w datasets

      - name: Run Python script
        env:
          MODEL_TYPE: ${{ inputs.model_type }}
          EPOCH_NUMBER: ${{ inputs.epoch_number }}
          BATCH_SIZE: ${{ inputs.batch_size }}
          TEST_IMAGE_NAME: "datasets/Flicker8k_Dataset/1001773457_577c3a7d70.jpg"
        run: |
          if [[ "$MODEL_TYPE" == "LSTM" ]]; then
            pipenv run python BaselineModel.py $EPOCH_NUMBER $BATCH_SIZE $TEST_IMAGE_NAME
          elif [[ "$MODEL_TYPE" == "Attention" ]]; then
            pipenv run python ImageCaptionGenerator.py $EPOCH_NUMBER $BATCH_SIZE $TEST_IMAGE_NAME
          else
            echo "Invalid MODEL_TYPE specified."
            exit 1
          fi
