name: Python CI

on:
  workflow_dispatch:
    inputs:
      epoch_number:
        description: 'Epoch number'
        required: true
        default: '10'
        type: choice
        options:
          - 10
          - 20
          - 50
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Python script
        run: python ImageCaptionGenerator.py
