name: Python CI

on:
  workflow_dispatch:
    inputs:
      epoch_number:
        description: 'Epoch number'
        required: true
        default: '10'
        type: choice
        options:
          - 10
          - 20
          - 50
  # push:
  #   branches:
  #     - main

jobs:
  build:
    runs-on: ubuntu-latest
    if:  ${{ inputs.epoch_number }} 
    steps:
      - name: "Executing for Epoch ${{ inputs.epoch_number }}"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: "pipenv"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pipenv
        run: |
         python -m pip install --upgrade pipenv wheel

      - name: Install dependencies
        run: |
          pipenv install --deploy --dev --verbose

      - name: Checkout repository
        uses: actions/checkout@v2
  
      - name: Select option
        id: select_option
        run: echo "::set-output name=selected_option::{${{ github.event.inputs.selected_option }}"

      - name: Run Python script
        run: python ImageCaptionGenerator.py${{ steps.select_option.outputs.selected_option }}


