name: Python CI

on:
  workflow_dispatch:
    inputs:  
      model_type:
        description: 'Model type'
        required: true
        default: 'LSTM'
        type: choice
        options:
          - LSTM
          - Attention
      
      epoch_number:
        description: 'Epoch number'
        required: true
        default: '10'
        type: choice
        options:
          - 2
          - 5
          - 10
          - 50

      batch_size:
        description: 'Batch Size'
        required: true
        default: '14'
        type: choice
        options:
          - 5
          - 10
          - 14
          - 20
          - 32

      
  # push:
  #   branches:
  #     - main

jobs:
  build:
    runs-on: ubuntu-latest
    if:  ${{ inputs.epoch_number }} 
    steps:
      - name: "Executing for Epoch ${{ inputs.epoch_number }}"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: "pipenv"

      - name: Install pipenv
        run: |
         python -m pip install --upgrade pipenv wheel

      - name: Install dependencies
        run: |
          pipenv install --deploy --dev --verbose

      - name: Download text file
        run: curl -L -o download_ds_file.zip "https://drive.google.com/uc?export=download&id=1sIxT8WrW21vaQvUY3BLGnnmAY-ocZhpO"

      - name: Download ZIP file
        run: |
          wget -O file.zip "https://drive.google.com/uc?export=download&id=176wGCHHp2DpoDblsliEkX4fTpfQUbZOq"
      
      - name: Check if file exists
        run: |
          if [ -f "file.zip" ]; then
            echo "File downloaded successfully."
          else
            echo "File download failed."
            exit 1
          fi
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Run Python script
        env:
          MODEL_TYPE: ${{ inputs.model_type }}
          EPOCH_NUMBER: ${{ inputs.epoch_number }}
          BATCH_SIZE: ${{ inputs.batch_size }}
        run: pipenv run python ImageCaptionGenerator.py $MODEL_TYPE $EPOCH_NUMBER $BATCH_NUMBER


