name: Dataset Download

on:
  push:
    branches:
      - main

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Git LFS
        run: |
          curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
          sudo apt-get install git-lfs
          git lfs install

      - name: Download and extract dataset
        run: |
          mkdir -p data
          git lfs pull --include="Downloads/Flicker8k_Dataset.zip"
          mv Downloads/Flicker8k_Dataset.zip data/dataset.zip
          unzip -q data/dataset.zip -d data
